language: java
jobs:
  include:
    - stage: build
      script: mvn compile
    - stage: test
      script: mvn test
    - stage: deploy
      deploy:
      before_deploy: git push origin master:refs/heads/master
      script: mvn clean package -DskipTests
      provider: azure_web_apps
      on:
      branch: master
