language: java
jobs:
  include:
    - stage: build
      script: mvn compile
    - stage: test
      script: mvn test
    -stage: deploy
     deploy:
     provider: azure_web_apps
     site: jooz-service
