language: java
jobs:
  include:
    - stage: build
      script: mvn compile
    - stage: test
      script: mvn test
    - stage: deploy
      deploy:
      provider: azure_web_apps
      verbose: true
      on:
      branch: master
